BEGIN;
CREATE TABLE IF NOT EXISTS master_distribution_packages (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_type text NOT NULL CHECK(package_type IN('full','delta','hotfix','rollback')), data_domain text NOT NULL CHECK(data_domain IN('dangerous-goods','domestic-law','code-mapping','application-case','all')), source_release text NOT NULL, target_release text NOT NULL, generated_at timestamptz NOT NULL, schema_version text NOT NULL, base_record_count integer NOT NULL CHECK(base_record_count>=0), added_count integer NOT NULL CHECK(added_count>=0), changed_count integer NOT NULL CHECK(changed_count>=0), removed_count integer NOT NULL CHECK(removed_count>=0), expected_record_count integer NOT NULL CHECK(expected_record_count>=0), result_status text NOT NULL CHECK(result_status IN('healthy','warning','critical')), manifest_sha256 text NOT NULL CHECK(manifest_sha256~'^[a-f0-9]{64}$'), package_sha256 text NOT NULL CHECK(package_sha256~'^[a-f0-9]{64}$'), rollback_sha256 text NOT NULL CHECK(rollback_sha256~'^[a-f0-9]{64}$'), evidence_reference text NOT NULL, note text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','submitted','reviewed','returned','approved','published','verified','cancelled')), snapshot jsonb, snapshot_sha256 text CHECK(snapshot_sha256 IS NULL OR snapshot_sha256~'^[a-f0-9]{64}$'), created_by uuid NOT NULL REFERENCES users(id), submitted_by uuid REFERENCES users(id), submitted_at timestamptz, reviewed_by uuid REFERENCES users(id), reviewed_at timestamptz, review_note text NOT NULL DEFAULT '', approved_by uuid REFERENCES users(id), approved_at timestamptz, approval_note text NOT NULL DEFAULT '', published_by uuid REFERENCES users(id), published_at timestamptz, distribution_reference text NOT NULL DEFAULT '', verified_by uuid REFERENCES users(id), verified_at timestamptz, verification_note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(source_release<>target_release), CHECK(package_sha256<>rollback_sha256)
);
CREATE TABLE IF NOT EXISTS client_compatibility_tests (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), environment_id text NOT NULL, device_class text NOT NULL CHECK(device_class IN('desktop','smartphone','tablet')), browser text NOT NULL CHECK(browser IN('chrome','edge','safari','firefox')), browser_version text NOT NULL, os text NOT NULL, tested_at timestamptz NOT NULL, online_success boolean NOT NULL, offline_startup boolean NOT NULL, sync_success boolean NOT NULL, layout_success boolean NOT NULL, pdf_deep_link_success boolean NOT NULL, storage_success boolean NOT NULL, service_worker_success boolean NOT NULL, test_count integer NOT NULL CHECK(test_count>0), failure_count integer NOT NULL CHECK(failure_count>=0 AND failure_count<=test_count), status text NOT NULL CHECK(status IN('healthy','warning','critical')), warnings jsonb NOT NULL DEFAULT '[]'::jsonb, evidence_reference text NOT NULL, evidence_sha256 text NOT NULL CHECK(evidence_sha256~'^[a-f0-9]{64}$'), note text NOT NULL DEFAULT '', recorded_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS continuity_exercises (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outage_type text NOT NULL CHECK(outage_type IN('api','database','storage','network','authentication','master-sync','other')), started_at timestamptz NOT NULL, restored_at timestamptz NOT NULL, duration_minutes integer NOT NULL CHECK(duration_minutes>=0), manual_record_count integer NOT NULL CHECK(manual_record_count>=0), reentered_count integer NOT NULL CHECK(reentered_count>=0), conflict_count integer NOT NULL CHECK(conflict_count>=0), lost_count integer NOT NULL CHECK(lost_count>=0), duplicate_count integer NOT NULL CHECK(duplicate_count>=0), result_status text NOT NULL CHECK(result_status IN('healthy','warning','critical')), playbook_reference text NOT NULL, manual_export_sha256 text NOT NULL CHECK(manual_export_sha256~'^[a-f0-9]{64}$'), sync_evidence_sha256 text NOT NULL CHECK(sync_evidence_sha256~'^[a-f0-9]{64}$'), note text NOT NULL DEFAULT '', executor_user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'recorded' CHECK(status IN('recorded','reviewed','reconciled','verified','cancelled')), created_by uuid NOT NULL REFERENCES users(id), reviewed_by uuid REFERENCES users(id), reviewed_at timestamptz, review_note text NOT NULL DEFAULT '', reconciled_by uuid REFERENCES users(id), reconciled_at timestamptz, reconciliation_note text NOT NULL DEFAULT '', verified_by uuid REFERENCES users(id), verified_at timestamptz, verification_note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(restored_at>=started_at), CHECK(reentered_count+lost_count=manual_record_count)
);
CREATE TABLE IF NOT EXISTS distribution_continuity_reviews (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_release text NOT NULL, period_start date NOT NULL, period_end date NOT NULL, summary text NOT NULL, evidence_items jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','submitted','reviewed','returned','approved','cancelled')), snapshot jsonb, snapshot_sha256 text CHECK(snapshot_sha256 IS NULL OR snapshot_sha256~'^[a-f0-9]{64}$'), created_by uuid NOT NULL REFERENCES users(id), submitted_by uuid REFERENCES users(id), submitted_at timestamptz, reviewed_by uuid REFERENCES users(id), reviewed_at timestamptz, review_note text NOT NULL DEFAULT '', approved_by uuid REFERENCES users(id), approved_at timestamptz, approval_note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(period_end>=period_start)
);
CREATE INDEX IF NOT EXISTS master_distribution_status_idx ON master_distribution_packages(status,generated_at DESC);
CREATE INDEX IF NOT EXISTS client_compatibility_device_idx ON client_compatibility_tests(device_class,status,tested_at DESC);
CREATE INDEX IF NOT EXISTS continuity_exercises_status_idx ON continuity_exercises(status,result_status,restored_at DESC);
CREATE INDEX IF NOT EXISTS distribution_continuity_reviews_status_idx ON distribution_continuity_reviews(status,period_end DESC);
COMMIT;
